sudo: required

language: php

services:
  - docker

env:
#  - COMPOSE_VERSION=1.11.0 PHP_VERSION=7 MYSQL_VERSION=5.7
  - COMPOSE_VERSION=1.11.0 PHP_VERSION=7 MYSQL_VERSION=5.6
#  - COMPOSE_VERSION=1.11.0 PHP_VERSION=5.6 MYSQL_VERSION=5.7
  - COMPOSE_VERSION=1.11.0 PHP_VERSION=5.6 MYSQL_VERSION=5.6


before_install:
 - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
 - chmod +x docker-compose
 - sudo mv docker-compose /usr/local/bin

script:
  - cd tests
  - sed -i -e 's/{{PHP_VERSION}}/'"$PHP_VERSION"'/g' php-fpm/Dockerfile
  - docker-compose run test
  
notifications:
  email:
    recipients:
      - travis@ximdex.com
    on_success: change # default: change
    on_failure: always # default: always
